### ISSUE TITLE
Support n-dimensional vectors

### ISSUE THREAD

**Issue by almstrand** [google/vector_math.dart#146]
Can a new [Vector](https://github.com/google/vector_math.dart/blob/master/lib/src/vector_math/vector.dart) class be added that represents a vector of arbitrary length?

It seems the current implementation of classes [Vector2](https://github.com/google/vector_math.dart/blob/master/lib/src/vector_math/vector2.dart), [Vector3](https://github.com/google/vector_math.dart/blob/master/lib/src/vector_math/vector2.dart), and [Vector4](https://github.com/google/vector_math.dart/blob/master/lib/src/vector_math/vector2.dart) can be generalized to form a new class `VectorN`, which would also implement [Vector](https://github.com/google/vector_math.dart/blob/master/lib/src/vector_math/vector.dart).

Clearly, 2, 3, and 4 dimensional vectors are sufficient for many applications. However there are applications where this restriction becomes prohibitive. The options for overcoming this restriction include creating another pub package, or a custom implementation in the application itself; neither of which promotes re-use, nor settling on a common package for solving a very common problem.

As an example, pub package [math_expressions](https://github.com/fkleon/math-expressions) has the set goal of "[...]supporting real, vector and interval evaluations of mathematical expressions." As the package depends on `vector_math` it is currently limited to evaluating expressions involving up to 4-dimensional vectors. [An issue](https://github.com/fkleon/math-expressions/issues/3) has been filed to look into options for eliminating this limitation. One of the options is for `math_expressions` to add a class that implements [Vector](https://github.com/google/vector_math.dart/blob/master/lib/src/vector_math/vector.dart) and represents vectors of arbitrary length, but it seems such a class would better belong in`vector_math` to promote standardizing on a singe package for representing vectors of all types.

**Comment by johnmccutchan** [comment]
Adding general size matrix / vector types to vector_math could happen but probably won't happen anytime soon because it is a lot of work.
