### ISSUE TITLE
Matrix4 has no equality operator.  Should either throw exception or have one.

### ISSUE THREAD

**Issue by eseidelGoogle** [google/vector_math.dart#147]
Right now it's confusing that this fails:
expect(new Matrix4.identity(), equals(new Matrix4.identity()))

Seems that Matrix4 should either throw an exception there (to catch naive users like myself) or should actually have a working equals operator.

**Comment by Fox32** [comment]
As we started to implement them for the vector classes, I don't see a problem not to implement them (except that comparing floating points might not be "fun").

I can look at it

**Comment by Fox32** [comment]
This issue is resolved and can be closed @kevmoo
