### ISSUE TITLE
Aabb2 does not enforce max.x >= min.x or max.y >= min.y 

### ISSUE THREAD

**Issue by ArgentiApparatus** [google/vector_math.dart#154]
It's possible to reverse the max and min inputs when creating a Aabb2, which leads to problems. E.g.

    Aabb2 x = new Aabb2.minMax(new Vector2(2.0, 2.0), new Vector2(-2.0, -2.0));  // Min, max reversed
    Aabb2 y = new Aabb2.minMax(new Vector2(-1.0, -1.0), new Vector2(1.0, 1.0));
    print(x.containsAabb2(y)); // False

similarly, the halfextents vector x and y coordinates may be < 0; 

    Aabb2 z = new Aabb2.centerAndHalfExtents(new Vector2.zero(), new Vector2(-1.0, -1.0));
    print(z.min); // [1.0,1.0]
    print(z.max); // [-1.0,-1.0]

I note that there is an intention to maintain min and max through rotation (but see #153).

    Aabb2 w = new Aabb2.centerAndHalfExtents(new Vector2.zero(), new Vector2(2.0, 1.0));
    print(w.min); // [-2.0,-1.0]
    print(w.max); // [2.0,1.0]
    w.rotate(new Matrix3.rotationZ((PI/2)));
    print(w.min); // [-1.0,-2.0]
    print(w.max); // [1.0,2.0]

Solution?

`Aabb2.centerAndHalfExtents()` could simply take the absolute value of the half extents vector.

I would suggest removing

    Aabb2.minMax(Vector2 min, Vector2 min)

and replacing it with something like

    Aabb2.around(Vector2 a, Vector2 b)

which should construct a minimal Aabb2 to include a and b. Also possibly  

    Aabb2.around(Iterable<Vector2> a)

 Or at least putting a huge warning in the documentation for `Aabb2.minMax(Vector2 min, Vector2 min)`.

**Comment by johnmccutchan** [comment]
@ArgentiApparatus 

- The minMax constructor can be misused. I agree that a large documentation warning makes sense. Please send a pull request.
- Adding a 'around' constructor (maybe named 'hull' that takes an arbitrary number of points) sounds good. Please send a pull request.

Thanks for the detailed feedback!

**Comment by Fox32** [comment]
I don't think that we want to add a check with an exception, but a checked mode assert would be fine. Should also be added to AABB3.

**Comment by ArgentiApparatus** [comment]
I'll work up a pull request for `Aabb2.minMax()` documentation at least.

What about my suggestion for `Aabb2.centerAndHalfExtents()` ?

**Comment by johnmccutchan** [comment]
Closing as stale.
