### ISSUE TITLE
Is setPerspectiveMatrix correct?

### ISSUE THREAD

**Issue by udhos** [google/vector_math.dart#155]
I suspect vector_math setPerspectiveMatrix() is wrong.

I was getting odd perspectives with setPerspectiveMatrix(), then I switched to
glmatrix mat4.perspective():
https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/mat4.js

Please compare those functions.
I am comparing their algorithms, not the languages (Dart is of course distintct from javascript).
The math use is different for each case, and I can confirm they produce distinct results.

**Comment by johnmccutchan** [comment]
Can you please provide a test case which demonstrates that vector_math is producing the *wrong* value?

**Comment by udhos** [comment]
Sorry, I don't have a handy test case to show how current vector_math setPerspectiveMatrix() produces unusual projection.

I noticed the distinction because scenes from my project seemed much closer with setPerspectiveMatrix() than in other renderers, for similar parameters.

However I can show the code I am now using translated to Dart/vector_math:

    // vector_math setPerspectiveMatrix() rewritten to be compatible with many other libs
    void setPerspectiveMatrix2(Matrix4 perspectiveMatrix, double fovYRadians,
        double aspectRatio, double zNear, double zFar) {

    	double f = Math.tan(Math.PI*0.5 - fovYRadians*0.5); // f = cotan(fovYRadians/2)
    	double rangeInv = 1.0 / (zNear - zFar);
    
     	double d0 = f / aspectRatio;
    	double d10 = (zNear + zFar) * rangeInv;
    	double d14 = zNear * zFar * rangeInv * 2.0;
    
    	perspectiveMatrix.setValues(
    		d0, 0.0, 0.0, 0.0,
    		0.0, f, 0.0, 0.0,
    		0.0, 0.0, d10, -1.0,
    		0.0, 0.0, d14, 0.0
    	);
    }

**Comment by johnmccutchan** [comment]
Assumed stale.
