### ISSUE TITLE
Release timeline

### ISSUE THREAD

**Issue by fkleon** [google/vector_math.dart#157]
The current version of `vector_math` available on pub is quite outdated compared to master. Is there a timeline for future releases, and would it be possible to prepare a new release with the fixes merged since 1.4.3?

The newest version of my library `math_expressions` depends on some of the changes made since 1.4.3 was released, and the pub dependency to a git repository leads to certain problems such as fkleon/math-expressions#4 - which is why that approach is not recommended in the first place. Unfortunately I don't see a way around this without a new release of `vector_math` to pub.

**Comment by johnmccutchan** [comment]
I just released 1.4.4 on pub

**Comment by Fox32** [comment]
I think 1.4.4 contains breaking changes as #145 was merged before?
