### ISSUE TITLE
Matrix constructor that takes a list

### ISSUE THREAD

**Issue by Hixie** [google/vector_math.dart#159]
I have code where I ended up doing:
```dart
Matrix4 transform = Function.apply(new Matrix4#, matrixArray);
```
...where `matrixArray` is a list of 16 doubles.

It would be cleaner if there was a constructor I could call that took care of this for me.

**Comment by johnmccutchan** [comment]
Added MatrixX.fromList constructors in 1.4.6 which was just released.

**Comment by Hixie** [comment]
You are awesome.
