### ISSUE TITLE
transform3 does not divide the result by w

### ISSUE THREAD

**Issue by abarth** [google/vector_math.dart#162]
When transforming `(x, y, z)` by a 4x4 matrix, I would have expect the result to be normalized by w.  Specifically, let `(x', y', z', w') = M * (x, y, z, 1.0)`, I would have expected the result to be `(x'/w', y'/w', z'/w')`.  The current implementation of `transform3` appears to throw away `w'`.

https://github.com/google/vector_math.dart/blob/master/lib/src/vector_math_64/matrix4.dart#L1744

@johnmccutchan

**Comment by johnmccutchan** [comment]
Matrix4.perspectiveTransform should do what you need

**Comment by abarth** [comment]
Thanks!
