### ISSUE TITLE
Replace dependency on quiver with own hash functions

### ISSUE THREAD

**Issue by Hixie** [google/vector_math.dart#163]
vector_math depends on quiver for its hash functions (as of https://github.com/google/vector_math.dart/commit/dc4916a81fa520bfdb8f73fd4c35a143c5e10dc1). Flutter depends on vector_math, but we'd like to avoid also importing quiver since it's quite large.

It would be nice if instead of using quiver, vector_math could use its own hash functions.

See also https://github.com/dart-lang/sdk/issues/25217

cc @abarth

**Comment by johnmccutchan** [comment]
This is now done.
