### ISSUE TITLE
Matrix4.leftTranslate

### ISSUE THREAD

**Issue by abarth** [google/vector_math.dart#166]
Matrix4.translate is great when you want to multiple in a translation on the right of a matrix, but sometimes you need to multiple a translation in on the left.  It would be valuable if there was a version of Matrix4.translate that applied the translation on the left (e.g., leftTranslate).

/cc @johnmccutchan

**Comment by johnmccutchan** [comment]
@abarth Please confirm that this commit fixes this issue:

https://github.com/google/vector_math.dart/commit/369422c70a96addf06a1cfd4757ef9402ed132f9

**Comment by abarth** [comment]
Yes, perfect.  Thank you.

**Comment by johnmccutchan** [comment]
@abarth vector_math 2.0.3 on pub contains Matrix4.leftTranslate.
