### ISSUE TITLE
Matrix4.isIdentity

### ISSUE THREAD

**Issue by abarth** [google/vector_math.dart#167]
We've got http://docs.flutter.io/flutter/painting/MatrixUtils/isIdentity.html in Flutter, but it seems like something that would make more sense as a getter on Matrix4.

No rush at all, but I wanted to file this feature request.  Thanks!

/cc @johnmccutchan

**Comment by johnmccutchan** [comment]
Implemented here https://github.com/google/vector_math.dart/commit/6d6839709164019f2643f390e2b8f5734b121668 I'm going to hold off on doing a vector_math pub release though.

**Comment by abarth** [comment]
Thanks.  Yeah, no rush on the release.
