### ISSUE TITLE
Support for frustrumfrustum

### ISSUE THREAD

**Issue by abarth** [google/vector_math.dart#168]
It's common to use a viewing frustum when using projective matrices in graphics (e.g., for use in GL).  It would be useful if `Matrix4` had constructors to make this easy.

I can try to work up a patch.

/cc @johnmccutchan

**Comment by abarth** [comment]
See http://www.songho.ca/opengl/gl_projectionmatrix.html for the math.

**Comment by Fox32** [comment]
Aren't the methods in https://github.com/abarth/vector_math.dart/blob/master/lib/src/vector_math/opengl.dart sufficient?

**Comment by abarth** [comment]
Ah, those looks pretty good.  I didn't know about them because they were in a separate library.
