### ISSUE TITLE
Vector.random constructor

### ISSUE THREAD

**Issue by hermanbergwerf** [google/vector_math.dart#170]
I found myself in a situation where I had to generate a random vector. I currently have a little utility function for this but it would be useful if there is a `Vector.random([Vector3 range])` constructor.

**Comment by johnmccutchan** [comment]
Feel free to send a pull request. I'd prefer:

Vector?.random() which fills the vector with random values between 0.0 and 1.0.

**Comment by hermanbergwerf** [comment]
Sure! So I should add a random constructor to `Vector2`, `Vector3` and `Vector4` in both `vector_math` and `vector_math_64`, right?

**Comment by Fox32** [comment]
For the constructor, one should be able to optionally supply an own instance of the Random class, like it's done in List.shuffle().

You only have to add it to vector_math. Afterwards you run the tool/generate_vector_math_64.dart script to generate a fresh vector_math_64 copy with our changes. Don't forget to write tests and format your code with the dart formatter.

**Comment by hermanbergwerf** [comment]
Closed in #172
