### ISSUE TITLE
Vector.ones constructor

### ISSUE THREAD

**Issue by hermanbergwerf** [google/vector_math.dart#171]
For computing a `(1/x, 1/y, 1/z)` vector it would be useful to have a `Vector.ones` constructor (e.g. `new Vector3.ones().divide(other)`).

**Comment by Fox32** [comment]
We already have `new Vector3.all(1)` which is as long as your suggestion, but much more universal.

**Comment by hermanbergwerf** [comment]
Sorry, missed that one.

**Comment by juanitogan** [comment]
Well, um, `Vector3.one()` seems to be nearly as common as `Vector3.zero()` (which does exist here) in my Unity work.  Many vector use cases move between 0 and 1.
