### ISSUE TITLE
Pardon, but you have no normal support?

### ISSUE THREAD

**Issue by acterhd** [google/vector_math.dart#176]
I looked in source code, and docs, but not found about normals of sphere from intersection point or (ray + distance). 

Also I can't found in library : random in sphere and hemisphere. :(

**Comment by Fox32** [comment]
No, I think you are right, we don't have that - looks like nobody was I need for this up till now. But feel free to send a Pull Request.

**Comment by acterhd** [comment]
For normal of sphere:
(origin - center) / radius
I don't know how restrict origin as intersection.

**Comment by johnmccutchan** [comment]
Please send a pull request.
