### ISSUE TITLE
errors when compiling with dartdevc

### ISSUE THREAD

**Issue by robertmuth** [google/vector_math.dart#179]
seems to be limited to src/vector_math/third_party/noise.dart

[error] Couldn't infer type parameter 'E'; 'int' must be of type 'double'. (package:vector_math/src/vector_math/third_party/noise.dart, line 31, col 5)
[error] The element type 'int' can't be assigned to the list type 'double'. (package:vector_math/src/vector_math/third_party/noise.dart, line 31, col 6)
[error] The element type 'int' can't be assigned to the list type 'double'. (package:vector_math/src/vector_math/third_party/noise.dart, line 31, col 9)
[error] The element type 'int' can't be assigned to the list type 'double'. (package:vector_math/src/vector_math/third_party/noise.dart, line 31, col 12)

**Comment by lexaknyazev** [comment]
Could you check dartdevc with #180 PR?

**Comment by robertmuth** [comment]
Thanks for the fast turnaround, Alexey.
The change works for me.

**Comment by lexaknyazev** [comment]
@robertmuth 
Seems like this issue could be closed now.
