### ISSUE TITLE
ddc complains about missing type annotations

### ISSUE THREAD

**Issue by robertmuth** [google/vector_math.dart#181]
Error compiling dartdevc module:vector_math|lib/lib__vector_math.js

[error] Missing parameter type for 'calculated'. (package:vector_math/src/vector_math/error_helpers.dart, line 10, col 22)
[error] Missing parameter type for 'correct'. (package:vector_math/src/vector_math/error_helpers.dart, line 10, col 34)
[error] Missing parameter type for 'calculated'. (package:vector_math/src/vector_math/error_helpers.dart, line 21, col 22)
[error] Missing parameter type for 'correct'. (package:vector_math/src/vector_math/error_helpers.dart, line 21, col 34)
[error] Missing variable type for 'outPx'. (package:vector_math/src/vector_math/frustum.dart, line 200, col 9)
[error] Missing variable type for 'outPy'. (package:vector_math/src/vector_math/frustum.dart, line 200, col 16)
[error] Missing variable type for 'outPz'. (package:vector_math/src/vector_math/frustum.dart, line 200, col 23)
[error] Missing variable type for 'outNx'. (package:vector_math/src/vector_math/frustum.dart, line 200, col 30)
[error] Missing variable type for 'outNy'. (package:vector_math/src/vector_math/frustum.dart, line 200, col 37)
[error] Missing variable type for 'outNz'. (package:vector_math/src/vector_math/frustum.dart, line 200, col 44)
[error] Missing return type for 'setEntry'. (package:vector_math/src/vector_math/matrix2.dart, line 44, col 3)
[error] Missing parameter type for 'other'. (package:vector_math/src/vector_math/matrix2.dart, line 148, col 20)
[error] Missing return type for '*'. (package:vector_math/src/vector_math/matrix2.dart, line 217, col 3)
[error] Missing return type for 'setEntry'. (package:vector_math/src/vector_math/matrix3.dart, line 91, col 3)
[error] Missing parameter type for 'other'. (package:vector_math/src/vector_math/matrix3.dart, line 238, col 20)
[error] Missing return type for '*'. (package:vector_math/src/vector_math/matrix3.dart, line 327, col 3)
[error] Missing return type for 'setEntry'. (package:vector_math/src/vector_math/matrix4.dart, line 162, col 3)
[error] Missing parameter type for 'other'. (package:vector_math/src/vector_math/matrix4.dart, line 516, col 20)
[error] Missing parameter type for 'x'. (package:vector_math/src/vector_math/matrix4.dart, line 656, col 18)
[error] Missing parameter type for 'x'. (package:vector_math/src/vector_math/matrix4.dart, line 694, col 22)
[error] Missing parameter type for 'x'. (package:vector_math/src/vector_math/matrix4.dart, line 846, col 14)
[error] Missing parameter type for 'x'. (package:vector_math/src/vector_math/matrix4.dart, line 880, col 18)
[error] Missing parameter type for 'other'. (package:vector_math/src/vector_math/vector2.dart, line 93, col 20)
[error] Missing variable type for 'sum'. (package:vector_math/src/vector_math/vector2.dart, line 145, col 9)
[error] Missing parameter type for 'other'. (package:vector_math/src/vector_math/vector3.dart, line 101, col 20)
[error] Missing parameter type for 'other'. (package:vector_math/src/vector_math/vector4.dart, line 121, col 20)

Please fix all errors before compiling (warnings are okay).

**Comment by lexaknyazev** [comment]
@robertmuth
Could you try DDC build with #182?

**Comment by robertmuth** [comment]
I tried with 
  vector_math:
       git:
         url: https://github.com/lexaknyazev/vector_math.dart
         ref: strong-mode
and that worked beautifully - thanks!
