### ISSUE TITLE
Is there a way to do Quaternion slerp interpolation ?

### ISSUE THREAD

**Issue by jox81** [google/vector_math.dart#184]
Hello, 
I'm trying to find an interpolation between 2 Quaternions using the next method : 

```
Quaternion result = v0 + t*(v1 - v0);
```

But a quaternion can't be mutliplied by a scalar.
Is there another way to do that ?

Thanks

**Comment by laszlokorte** [comment]
`q0 + (q1 - q0).scaled(t)`

https://github.com/google/vector_math.dart/blob/master/lib/src/vector_math/quaternion.dart#L376

**Comment by jox81** [comment]
oh... yes, pretty simple in fact :-) Thank you
