### ISSUE TITLE
Publish 2.0.8

### ISSUE THREAD

**Issue by leafpetersen** [google/vector_math.dart#192]
It looks like 2.0.8 contains changes required for Dart 2 but hasn't been published yet.  Consider publishing a new version, possibly with a < 3.0 SDK constraint?

**Comment by johnmccutchan** [comment]
You should now have permission to publish.

**Comment by chalin** [comment]
Publishing soon? /cc @kevmoo

**Comment by tvolkert** [comment]
Done
