### ISSUE TITLE
hashCode for Vector3 etc do not work well

### ISSUE THREAD

**Issue by robertmuth** [google/vector_math.dart#198]
If two vectors are close to zero they will map to "0" in the current hashCode implementation.
A better approach would be something like this:

int hashVector3(VM.Vector3 v) {
  int h = 0;
  for (int i in v.storage.buffer.asInt32List()) {
    h ^= i;
  }
  return h;
}

**Comment by johnmccutchan** [comment]
Please provide a pull request with unit tests.

**Comment by rakudrama** [comment]
Is this fixed by the fix for https://github.com/dart-lang/sdk/issues/35116?

**Comment by robertmuth** [comment]
@john
I am not the right person to create the pull request.  It will probably take me hours to familiarize
myself with the code base and test framework, while it should take only minutes for somebody
more familiar with the project. Also, I do not plan on submitting a lot of pull requests in the future
so the learning effort would never pay dividends.

**Comment by rakudrama** [comment]
@robertmuth There have been changes in the hashCode of numbers. Can you verify that this is still a problem?

**Comment by robertmuth** [comment]
I just tracked this down for Vector3. We have

class Vector3 implements Vector {
  final Float32List _v3storage;
  ...

  @override
  int get hashCode => quiver.hashObjects(_v3storage);
  ...
}

elsewhere we have

import 'hash.dart' as quiver;

where hash.dart is this file:
https://github.com/google/vector_math.dart/blob/master/lib/hash.dart

The code for  hashObjects is a functional programmers dream, incomprehensible, 
and probably wrong.
If I understand the code correctly, we are still passing in a List<double> and
each double gets  implicitly converted to int.

**Comment by rakudrama** [comment]
@robertmuth
The code was [changed in January](https://github.com/dart-lang/sdk/commit/ea6d343bae03d8de3662e1467a94f0d13897a8ba), and I commented to that effect above in April.
The intention of the change is that `double`s are not implicitly converted to `int` while maintaining that equal values (`1` and `1.0`) have the same hash code.
So does the hashCode for Vector3 still not work well?
Presumably your initial report came from some experience that you could revisit.

**Comment by robertmuth** [comment]
The sad part is that I do not  remember where I encountered it anymore.

But  if  hash of Vector3(0.1, 0.1, 0.1)  != hash of Vector3(0.2, 0.2, 0.2)
the problem has been fixed and I stay corrected.

BTW: I see now the  "i.hashCode" part in hashObjects so yeah there is no
          double to int conversion - my mistake.

**Comment by robertmuth** [comment]
I did some spot checking and the problem is gone.

**Comment by rakudrama** [comment]
Thanks!
