### ISSUE TITLE
Advice on draw mesh to screen - Canvas drawing primitives?

### ISSUE THREAD

**Issue by camillo777** [google/vector_math.dart#220]
Hello,
Fantastic library, I was planning to start using it, I was wondering what is the best way to draw on screen with this library on Flutter.
Just using Canvas drawing primitives and implementing myself the drawing for faces/vertices or is there some other more optimised library for doing it? 
Thank you
Camillo

**Comment by FlorisDevreese** [comment]
Hi @camillo777 
I'm also looking to find a library to draw a 2D mesh.
Till now without success.
Did you find anything?

**Comment by johnmccutchan** [comment]
Hi, this is outside the scope of vector_math package.
