### ISSUE TITLE
Overflowed issue

### ISSUE THREAD

**Issue by wenshisan** [google/vector_math.dart#237]
![QQ图片20201105182811](https://user-images.githubusercontent.com/13963679/98229293-b22f5780-1f94-11eb-9c46-862cdfa26475.png)
Like image shows above, when use Math.text like this `   Flexible(
                child: Math.tex(
              t.data,
              mathStyle: MathStyle.display,
              settings: TexParserSettings(displayMode: true),
              textStyle: TextStyle(color: Colors.blue[200]),
            ))`
i got a broken ui, everything was normal when use Text widget anywhere i missed settings?

**Comment by johnmccutchan** [comment]
This doesn't seem related to vector_math package.
