### ISSUE TITLE
Aab3 intersects with plane fails

### ISSUE THREAD

**Issue by jamesblasco** [google/vector_math.dart#260]
I am trying to intersect a bounding box with a z plane that passes the center of the bounding box, but it returns false:

Demo: 
```dart
import "package:vector_math/vector_math_64.dart";
  
  
void main() {
  final box = Aabb3.minMax(Vector3(-20.0, -50, 32),Vector3(36, -32, 8));
   
  final intersects = box.intersectsWithPlane(
     Plane.normalconstant(
      Vector3(0, 0, 1),
      box.center.z
   ));
   assert(intersects);
}
```

https://dartpad.dartlang.org/?id=bc74e7250778bb0d2e4b3792ed2bde25

-----

# Debugging the code

<img width="601" alt="Screenshot 2022-03-06 at 11 20 51" src="https://user-images.githubusercontent.com/19904063/156918970-599be900-00b0-42a4-94b3-8b6cf6d204f8.png">

Checking the code I realize the comment says:

>  // Intersection occurs when distance s falls within [-r,+r] interval

When setting a breakpoint I can see that s:0  and r: -12. This meets the condition from the comment.
But the logic inside the if the condition (`s.abs() <= r`) fails . Should it be?

```dart
if (s.abs() <= r.abs()) {
```

<img width="474" alt="Screenshot 2022-03-06 at 11 12 53" src="https://user-images.githubusercontent.com/19904063/156918708-ec1eca1c-b1a9-4b2f-bcc1-9cec9ffda012.png">

**Comment by GhostCore07** [comment]
your min vector has a larger z than the max vector, if you swap them it works
