### ISSUE TITLE
Quaternion unary - takes the conjugate instead of memberwise negation

### ISSUE THREAD

**Issue by AsturaPhoenix** [google/vector_math.dart#276]
Currently quaternion negation takes the conjugate rather than scaling by -1, which was surprising to me and doesn't seem consistent with binary operator -, which indeed subtracts memberwise.

This seems to be a regression introduced many years ago at https://github.com/google/vector_math.dart/commit/e7bf99e668fd680d2c0deba9b5b61d406868abd3#diff-f11831298dd6e7900532989a327b8f1934d513eb3e33faa366c68c1a44227c5eR377

This applies to both `vector_math` and `vector_math_64`.

**Comment by johnmccutchan** [comment]
Hi,

Please send a PR to fix the issue.
