### ISSUE TITLE
Does Vector2 perform SIMD instructions on computation?

### ISSUE THREAD

**Issue by shtse8** [google/vector_math.dart#285]
I understand Float64x2 and other typed data can perform SIMD to speed up the calculation.
But Vector2 is using Float64List which I couldn't find any information after many search on internet.
I would like to know if Vector2 can perform SIMD operations?
Thanks.

**Comment by johnmccutchan** [comment]
The implementation of Vector2 doesn't use SIMD instructions as using SIMD instructions for "one off" computations is rarely a performance win. SIMD is best used in tight loops operating on contiguous data.

**Comment by shtse8** [comment]
> The implementation of Vector2 doesn't use SIMD instructions as using SIMD instructions for "one off" computations is rarely a performance win. SIMD is best used in tight loops operating on contiguous data.

Does it mean letting optimization to optimize to SIMD instead of calling "one off" computations? How can we know if the optimizer did the job?
