### ISSUE TITLE
Call chaining support

### ISSUE THREAD

**Issue by Fox32** [google/vector_math.dart#59]
I think call/method chaining is a nice feature and even better, Dart comes with support for that! So how about dropping the call chaining support in vector_math?

Pro:
* Why adding something that is already supported?
* Better distinction between methods that return itself for chaining and methods that really return a new instance: For example, normalize vs normalized. I know that there is already the naming convention, but it could be easier.

Cons:
* BREAKING CHANGE
* Typing one more '.'?
* Work, programmers are lazy (but I could do it, if we decide to go this way)

I'm not sure about the performance influence of this change. This is something for a person with in-depth knowledge. Maybe there was a good reasons forthe decision to implement call chaining (or Dart doesn't supported it back then).

**Comment by Fox32** [comment]
I wonder if removing call chaining is still an option. I could send a PR for this, or skip it.

**Comment by johnmccutchan** [comment]
Assuming that performance isn't impacted, we should stop returning this and use method cascading.

**Comment by Fox32** [comment]
Good, than I will do a PR for that

**Comment by johnmccutchan** [comment]
Thanks @Fox32

**Comment by Fox32** [comment]
Wow that was fast =)
