### ISSUE TITLE
Proposal to add setFromUnitVectors and dot methods to Quaternion library

### ISSUE THREAD

**Issue by adamjcook** [google/vector_math.dart#79]
I am working on porting some of the controls from the three.js engine into three.dart and I noticed that some of the "convenience" methods that were included in three.js's Quaternion library did not make it into this project (understandably so). Please let me know if I missed them.

Therefore, I was wondering if you would like to accept them into your project?  The methods I am referring to are:

* Quaternion.setFromUnitVectors( vFrom, vTo ) [Reference Documentation](http://threejs.org/docs/#Reference/Math/Quaternion) - yields the quaternion describing the rotation between the two directional unit vectors that are provided. The three.js project authors seem to have adopted it from an implementation discussed [here](http://lolengine.net/blog/2014/02/24/quaternion-from-two-vectors-final).

* Quaternion.dot( v ) - dot product of two quaternions.

Curiously enough, I could not find the second method (.dot()) in the three.js documentation, but it is shown in the source [here](https://github.com/mrdoob/three.js/blob/master/src/math/Quaternion.js#L316). 

If you think that these are a good fit for this project, I can certainly provide a PR.

Please see my rather hackish implementations here:

* [setFromUnitVectors](https://github.com/adamjcook/three.dart/blob/orbit/lib/extras/controls/orbit_controls.dart#L730)
* [dot](https://github.com/adamjcook/three.dart/blob/orbit/lib/extras/controls/orbit_controls.dart#L764)

I will, of course, clean these up to conform to the existing vector_math project source and style on a PR.

Please let me know if this of interest.

**Comment by johnmccutchan** [comment]
Hi,

Please send a pull request with some tests.

John
