### ISSUE TITLE
Make AABB classes based on center + half instead of min + max

### ISSUE THREAD

**Issue by ceronman** [google/vector_math.dart#82]
In my experience, most common AABB operations, including transformations and collision detection and response, use center + half more often than min + max, or position + size.

Because the current implementation is based on min + max vectors, many times it's required to allocate new vectors and use `copyCenterAndHalfExtents`.

Basing the class on center + half vectors would allow for some very small optimization, but most importantly it would make the API nicer.

I would like to read opinions on the matter.

**Comment by johnmccutchan** [comment]
Switching the internal representation to be center + half extends sounds like a good idea.

**Comment by Fox32** [comment]
Some of the intersection tests are already implemented with this change in mind.

**Comment by johnmccutchan** [comment]
*ping*

**Comment by ceronman** [comment]
Pong. Sorry I don't have to work on this at the moment. Feel free to close the issue.
